#!/bin/bash

valac --vapidir=vapi --Xcc=-lm --target-glib 2.32 --pkg gtk+-3.0 --pkg glib-2.0 --pkg libnotify --pkg gio-2.0 --pkg gee-1.0 --pkg gmodule-2.0 --pkg libxml-2.0 --pkg webkitgtk-3.0 --pkg libsoup-2.4 --pkg json-glib-1.0 --thread ./src/*.vala -o ./bin/gnome-sms-client

# Debug: -g --save-temps
# echo "blub" | nc localhost 3333
